# Generated by Django 5.2.4 on 2025-07-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', 'O‘rta'), ('high', 'Yuqori')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
